import { describe, it, expect } from "vitest";
import {
  FEATURE_DIM,
  FEATURE_SCHEMA_VERSION,
  buildFeatureVector,
  normalizeSequence,
  type Landmark,
} from "../featureSchema";
import fixture from "./crosscheckFixture.json";

/**
 * This test proves featureSchema.ts and ml_service/feature_schema.py agree
 * numerically on the SAME input, not just that each one is internally
 * self-consistent. The fixture (crosscheckFixture.json) was generated BY
 * the Python module (see ml_service/generate_crosscheck_fixture.py) --
 * Python is the source of truth here. If this test fails after editing
 * either file, one of the two schemas drifted from the other; regenerate
 * the fixture from Python and diff, don't just update the expected values
 * blindly.
 */

function toLandmarks(rows: number[][], withVisibility: boolean): Landmark[] {
  return rows.map((r) =>
    withVisibility ? { x: r[0], y: r[1], z: r[2], visibility: r[3] } : { x: r[0], y: r[1], z: r[2] }
  );
}

describe("featureSchema cross-language golden vector", () => {
  it("fixture was generated for the schema version this file implements", () => {
    expect(fixture.schema_version).toBe(FEATURE_SCHEMA_VERSION);
    expect(fixture.feature_dim).toBe(FEATURE_DIM);
  });

  it("buildFeatureVector matches feature_schema.py's build_feature_vector on identical input", () => {
    const leftHand = toLandmarks(fixture.left_hand, false);
    const rightHand = toLandmarks(fixture.right_hand, false);
    const pose = toLandmarks(fixture.pose, true);
    const face = toLandmarks(fixture.face, false);

    const vec = buildFeatureVector(leftHand, rightHand, pose, face);
    expect(vec.length).toBe(fixture.expected_feature_vector.length);

    for (let i = 0; i < vec.length; i++) {
      expect(vec[i]).toBeCloseTo(fixture.expected_feature_vector[i], 4);
    }
  });

  it("normalizeSequence matches feature_schema.py's normalize_sequence, including the pose-visibility passthrough", () => {
    const leftHand = toLandmarks(fixture.left_hand, false);
    const rightHand = toLandmarks(fixture.right_hand, false);
    const pose = toLandmarks(fixture.pose, true);
    const face = toLandmarks(fixture.face, false);
    const baseVec = buildFeatureVector(leftHand, rightHand, pose, face);

    const scales: number[] = fixture.sequence_frame_scales;
    const frames = scales.length;
    const flat = new Float32Array(frames * FEATURE_DIM);
    for (let f = 0; f < frames; f++) {
      for (let d = 0; d < FEATURE_DIM; d++) {
        flat[f * FEATURE_DIM + d] = baseVec[d] * scales[f];
      }
    }

    const normalized = normalizeSequence(flat, frames, FEATURE_DIM);
    const expected: number[][] = fixture.expected_normalized_sequence;

    for (let f = 0; f < frames; f++) {
      for (let d = 0; d < FEATURE_DIM; d++) {
        expect(normalized[f * FEATURE_DIM + d]).toBeCloseTo(expected[f][d], 3);
      }
    }
  });
});
