import { describe, it, expect } from "vitest";
import { markdownToPlainText, slugify, parseInlineRuns, buildDocxDocument } from "../notesExport";

describe("slugify", () => {
  it("lowercases and hyphenates a title", () => {
    expect(slugify("DBMS Lecture 04")).toBe("dbms-lecture-04");
  });

  it("strips characters that aren't safe in filenames", () => {
    expect(slugify("Q&A: What's Next?!")).toBe("q-a-what-s-next");
  });

  it("falls back to a default when the title has nothing usable", () => {
    expect(slugify("!!!")).toBe("sign2notes");
    expect(slugify("")).toBe("sign2notes");
  });

  it("accepts a custom fallback", () => {
    expect(slugify("", "live-session")).toBe("live-session");
  });
});

describe("markdownToPlainText", () => {
  it("includes the SIGN2NOTES header, title, and date", () => {
    const out = markdownToPlainText("# Notes\n- point one", { title: "DBMS Lecture 04" });
    expect(out).toContain("SIGN2NOTES");
    expect(out).toContain("DBMS Lecture 04");
    expect(out).toMatch(/Date: /);
  });

  it("includes duration only when provided", () => {
    const withDuration = markdownToPlainText("- x", { durationSeconds: 125 });
    expect(withDuration).toMatch(/Duration: 2:05/);
    const withoutDuration = markdownToPlainText("- x", {});
    expect(withoutDuration).not.toMatch(/Duration:/);
  });

  it("uppercases headings and bullets get a literal bullet character", () => {
    const out = markdownToPlainText("## Key Concepts\n- Definition discussed");
    expect(out).toContain("KEY CONCEPTS");
    expect(out).toContain("\u2022 Definition discussed");
  });

  it("strips markdown emphasis markers (plain text has no bold/italic)", () => {
    const out = markdownToPlainText("This is **bold** and *italic*.");
    expect(out).toContain("This is bold and italic.");
    expect(out).not.toContain("**");
  });

  it("ends with the generated-by footer disclaimer", () => {
    const out = markdownToPlainText("- x");
    expect(out).toContain("Generated by Sign2Notes");
  });
});

describe("parseInlineRuns", () => {
  it("returns a single plain run for text with no emphasis", () => {
    const runs = parseInlineRuns("just plain text");
    expect(runs).toEqual([{ text: "just plain text" }]);
  });

  it("splits bold text into its own run", () => {
    const runs = parseInlineRuns("hello **world** end");
    expect(runs).toEqual([
      { text: "hello " },
      { text: "world", bold: true },
      { text: " end" },
    ]);
  });

  it("splits italic text into its own run", () => {
    const runs = parseInlineRuns("hello *world* end");
    expect(runs).toEqual([
      { text: "hello " },
      { text: "world", italics: true },
      { text: " end" },
    ]);
  });

  it("handles multiple emphasis spans in one line", () => {
    const runs = parseInlineRuns("**A** and *B* and **C**");
    expect(runs.filter((r) => r.bold)).toHaveLength(2);
    expect(runs.filter((r) => r.italics)).toHaveLength(1);
  });

  it("handles a line that is entirely emphasized", () => {
    expect(parseInlineRuns("**all bold**")).toEqual([{ text: "all bold", bold: true }]);
  });

  it("handles an empty string without crashing", () => {
    expect(parseInlineRuns("")).toEqual([{ text: "" }]);
  });
});

describe("buildDocxDocument -- real DOCX generation", () => {
  it("produces a real ZIP/OOXML document, not a stub", async () => {
    const { Packer } = await import("docx");
    const doc = await buildDocxDocument("# Lecture Notes\n\n## Key Concepts\n- **Definition** discussed\n- *Example* given", {
      title: "DBMS Lecture 04",
      durationSeconds: 754,
    });
    const buf = await Packer.toBuffer(doc);

    // A real .docx is a ZIP container -- verify the actual magic bytes,
    // not just that Packer.toBuffer() resolved without throwing.
    expect(buf.length).toBeGreaterThan(500);
    expect(buf[0]).toBe(0x50); // 'P'
    expect(buf[1]).toBe(0x4b); // 'K'
  });

  it("does not throw on an empty notes string", async () => {
    const { Packer } = await import("docx");
    const doc = await buildDocxDocument("", { title: "Empty Session" });
    const buf = await Packer.toBuffer(doc);
    expect(buf[0]).toBe(0x50);
    expect(buf[1]).toBe(0x4b);
  });

  it("does not throw on notes containing many headings, bullets, and blank lines", async () => {
    const { Packer } = await import("docx");
    const markdown = [
      "# Title",
      "",
      "## Section One",
      "- point a",
      "- point b",
      "",
      "## Section Two",
      "Some **bold** paragraph text with *italic* too.",
      "",
      "- final point",
    ].join("\n");
    const doc = await buildDocxDocument(markdown);
    const buf = await Packer.toBuffer(doc);
    expect(buf.length).toBeGreaterThan(500);
  });
});
