/**
 * Canonical feature schema v2: "hand_body_face".
 *
 * This is the TypeScript twin of ml_service/feature_schema.py. A Python
 * module can't run in a browser, so the constants and logic are
 * re-expressed here -- but every constant and every function's behavior
 * must match the Python side exactly. This is enforced, not just hoped
 * for: `npm run schema:crosscheck` (see package.json) runs
 * featureSchema.crosscheck.test.ts, which feeds the SAME synthetic
 * landmark fixture (frontend/src/lib/__tests__/crosscheckFixture.json)
 * through this file's buildFeatureVector()/normalizeSequence() and
 * compares the result byte-for-byte against a vector generated by the
 * Python module (ml_service/tests/test_feature_schema.py generates that
 * fixture's expected output -- see "Cross-language golden vector" in
 * FEATURE_SCHEMA.md for exactly how the two are kept in sync).
 *
 * See feature_schema.py's docstring for the full rationale (Holistic vs.
 * separate detectors, why face is a reduced subset not the full mesh, why
 * pose visibility is excluded from z-scoring, etc.) -- it isn't repeated
 * here to avoid the two docs drifting apart; FEATURE_SCHEMA.md is the
 * canonical prose write-up both files point to.
 */

export const FEATURE_SCHEMA_VERSION = "2.0";
export const FEATURE_TYPE = "hand_body_face";

export interface Landmark {
  x: number;
  y: number;
  z: number;
  visibility?: number;
}

// ---------------------------------------------------------------------------
// LEFT_HAND / RIGHT_HAND -- 21 landmarks x (x, y, z) = 63 dims each
// ---------------------------------------------------------------------------
export const NUM_HAND_LANDMARKS = 21;
export const HAND_DIMS_PER_LANDMARK = 3;
export const HAND_FEATURE_DIM = NUM_HAND_LANDMARKS * HAND_DIMS_PER_LANDMARK; // 63

// ---------------------------------------------------------------------------
// POSE -- 9 selected landmarks x (x, y, z, visibility) = 36 dims
// ---------------------------------------------------------------------------
// MUST match feature_schema.py's POSE_LANDMARK_INDICES exactly, same order.
export const POSE_LANDMARK_NAMES = [
  "NOSE",
  "LEFT_SHOULDER",
  "RIGHT_SHOULDER",
  "LEFT_ELBOW",
  "RIGHT_ELBOW",
  "LEFT_WRIST",
  "RIGHT_WRIST",
  "LEFT_HIP",
  "RIGHT_HIP",
] as const;
export const POSE_LANDMARK_INDICES = [0, 11, 12, 13, 14, 15, 16, 23, 24];
export const POSE_DIMS_PER_LANDMARK = 4; // x, y, z, visibility
export const POSE_FEATURE_DIM = POSE_LANDMARK_INDICES.length * POSE_DIMS_PER_LANDMARK; // 36

// ---------------------------------------------------------------------------
// FACE -- 41 selected landmarks x (x, y, z) = 123 dims
// ---------------------------------------------------------------------------
// MUST match feature_schema.py's FACE_LANDMARK_GROUPS exactly -- same
// indices, same group order (HEAD_REFERENCE, EYEBROWS, EYES, LIPS), same
// order within each group.
export const FACE_LANDMARK_GROUPS: Record<string, Record<string, number>> = {
  HEAD_REFERENCE: {
    NOSE_TIP: 1,
    NOSE_BRIDGE: 168,
    NOSE_BOTTOM: 2,
    FOREHEAD: 10,
    CHIN: 152,
    LEFT_CHEEK: 234,
    RIGHT_CHEEK: 454,
  },
  EYEBROWS: {
    LEFT_EYEBROW_OUTER: 70,
    LEFT_EYEBROW_MID_OUTER: 63,
    LEFT_EYEBROW_MID: 105,
    LEFT_EYEBROW_MID_INNER: 66,
    LEFT_EYEBROW_INNER: 107,
    RIGHT_EYEBROW_INNER: 336,
    RIGHT_EYEBROW_MID_INNER: 296,
    RIGHT_EYEBROW_MID: 334,
    RIGHT_EYEBROW_MID_OUTER: 293,
    RIGHT_EYEBROW_OUTER: 300,
  },
  EYES: {
    LEFT_EYE_OUTER: 33,
    LEFT_EYE_TOP_OUTER: 160,
    LEFT_EYE_TOP_INNER: 158,
    LEFT_EYE_INNER: 133,
    LEFT_EYE_BOTTOM_INNER: 153,
    LEFT_EYE_BOTTOM_OUTER: 144,
    RIGHT_EYE_INNER: 362,
    RIGHT_EYE_TOP_INNER: 385,
    RIGHT_EYE_TOP_OUTER: 387,
    RIGHT_EYE_OUTER: 263,
    RIGHT_EYE_BOTTOM_OUTER: 373,
    RIGHT_EYE_BOTTOM_INNER: 380,
  },
  LIPS: {
    MOUTH_LEFT_CORNER: 61,
    UPPER_LIP_LEFT_OUTER: 40,
    UPPER_LIP_LEFT_INNER: 37,
    UPPER_LIP_CENTER: 0,
    UPPER_LIP_RIGHT_INNER: 267,
    UPPER_LIP_RIGHT_OUTER: 270,
    MOUTH_RIGHT_CORNER: 291,
    LOWER_LIP_RIGHT_OUTER: 321,
    LOWER_LIP_RIGHT_INNER: 314,
    LOWER_LIP_CENTER: 17,
    LOWER_LIP_LEFT_INNER: 84,
    LOWER_LIP_LEFT_OUTER: 91,
  },
};

function flattenGroups(groups: Record<string, Record<string, number>>): { names: string[]; indices: number[] } {
  const names: string[] = [];
  const indices: number[] = [];
  for (const group of Object.values(groups)) {
    for (const [name, idx] of Object.entries(group)) {
      names.push(name);
      indices.push(idx);
    }
  }
  return { names, indices };
}

const _face = flattenGroups(FACE_LANDMARK_GROUPS);
export const FACE_LANDMARK_NAMES = _face.names;
export const FACE_LANDMARK_INDICES = _face.indices;
export const FACE_DIMS_PER_LANDMARK = 3;
export const FACE_FEATURE_DIM = FACE_LANDMARK_INDICES.length * FACE_DIMS_PER_LANDMARK; // 123

// ---------------------------------------------------------------------------
// Full per-frame layout -- LEFT_HAND, RIGHT_HAND, POSE, FACE, in that order
// ---------------------------------------------------------------------------
export const FEATURE_GROUPS: Array<[string, number, number]> = [
  ["left_hand", 0, HAND_FEATURE_DIM],
  ["right_hand", HAND_FEATURE_DIM, 2 * HAND_FEATURE_DIM],
  ["pose", 2 * HAND_FEATURE_DIM, 2 * HAND_FEATURE_DIM + POSE_FEATURE_DIM],
  [
    "face",
    2 * HAND_FEATURE_DIM + POSE_FEATURE_DIM,
    2 * HAND_FEATURE_DIM + POSE_FEATURE_DIM + FACE_FEATURE_DIM,
  ],
];
export const FEATURE_DIM = 2 * HAND_FEATURE_DIM + POSE_FEATURE_DIM + FACE_FEATURE_DIM; // 285

const POSE_START = FEATURE_GROUPS[2][1];
export const POSE_VISIBILITY_INDICES = POSE_LANDMARK_INDICES.map((_, i) => POSE_START + 4 * i + 3);

export class FeatureSchemaError extends Error {}

export function assertFeatureDim(dim: number, context = ""): void {
  if (dim !== FEATURE_DIM) {
    const where = context ? ` (${context})` : "";
    const hint = dim === 126 ? " These look like old hand-only features (schema v1, 126 dims)." : "";
    throw new FeatureSchemaError(
      `Feature dimension mismatch${where}: got ${dim}, but the current feature schema is ` +
        `v${FEATURE_SCHEMA_VERSION} ('${FEATURE_TYPE}'), which expects ${FEATURE_DIM} dims per frame ` +
        `(${HAND_FEATURE_DIM} left hand + ${HAND_FEATURE_DIM} right hand + ${POSE_FEATURE_DIM} pose + ` +
        `${FACE_FEATURE_DIM} face).${hint} Re-run feature extraction, or reload a schema-v2-compatible model.`
    );
  }
}

// ---------------------------------------------------------------------------
// build one frame's feature vector
// ---------------------------------------------------------------------------

function flattenHand(landmarks: Landmark[] | null | undefined): Float32Array {
  const out = new Float32Array(HAND_FEATURE_DIM);
  if (!landmarks) return out;
  for (let i = 0; i < NUM_HAND_LANDMARKS && i < landmarks.length; i++) {
    out[i * 3] = landmarks[i].x;
    out[i * 3 + 1] = landmarks[i].y;
    out[i * 3 + 2] = landmarks[i].z;
  }
  return out;
}

function flattenSubset(
  landmarks: Landmark[] | null | undefined,
  indices: number[],
  dimsPerLandmark: number,
  includeVisibility: boolean
): Float32Array {
  const out = new Float32Array(indices.length * dimsPerLandmark);
  if (!landmarks) return out;
  for (let slot = 0; slot < indices.length; slot++) {
    const srcIdx = indices[slot];
    if (srcIdx >= landmarks.length) continue; // defensive: leave as zeros
    const lm = landmarks[srcIdx];
    const base = slot * dimsPerLandmark;
    out[base] = lm.x;
    out[base + 1] = lm.y;
    out[base + 2] = lm.z;
    if (includeVisibility) out[base + 3] = lm.visibility ?? 0;
  }
  return out;
}

/**
 * Build one canonical FEATURE_DIM-length vector for a single frame from
 * a HolisticLandmarker result's four landmark lists (already unwrapped to
 * the single tracked instance -- e.g. `result.leftHandLandmarks[0]`, not
 * the raw `NormalizedLandmark[][]`). Mirrors feature_schema.py's
 * build_feature_vector() exactly.
 */
export function buildFeatureVector(
  leftHand: Landmark[] | null | undefined,
  rightHand: Landmark[] | null | undefined,
  pose: Landmark[] | null | undefined,
  face: Landmark[] | null | undefined
): Float32Array {
  const left = flattenHand(leftHand);
  const right = flattenHand(rightHand);
  const poseVec = flattenSubset(pose, POSE_LANDMARK_INDICES, POSE_DIMS_PER_LANDMARK, true);
  const faceVec = flattenSubset(face, FACE_LANDMARK_INDICES, FACE_DIMS_PER_LANDMARK, false);

  const out = new Float32Array(FEATURE_DIM);
  out.set(left, 0);
  out.set(right, HAND_FEATURE_DIM);
  out.set(poseVec, 2 * HAND_FEATURE_DIM);
  out.set(faceVec, 2 * HAND_FEATURE_DIM + POSE_FEATURE_DIM);
  return out;
}

// ---------------------------------------------------------------------------
// Normalization -- mirrors feature_schema.py's normalize_sequence()/
// pad_or_trim()/prepare_window() exactly (including the pose-visibility
// exclusion and the trim-then-normalize-then-pad ordering).
// ---------------------------------------------------------------------------

const POSE_VIS_SET = new Set(POSE_VISIBILITY_INDICES);

/**
 * Per-dimension z-score over time (axis 0), excluding pose-visibility
 * dims (passed through, clipped to [0, 1]). `window` is a flat Float32Array
 * of length frames*dims (row-major: frame 0's `dims` values, then frame
 * 1's, ...) -- same convention the existing normalizeWindow() used, kept
 * so KeypointBuffer doesn't need a data-layout change.
 */
export function normalizeSequence(window: Float32Array, frames: number, dims = FEATURE_DIM): Float32Array {
  const mean = new Float64Array(dims);
  const std = new Float64Array(dims);
  for (let f = 0; f < frames; f++) {
    for (let d = 0; d < dims; d++) mean[d] += window[f * dims + d];
  }
  for (let d = 0; d < dims; d++) mean[d] /= frames;

  for (let f = 0; f < frames; f++) {
    for (let d = 0; d < dims; d++) {
      const diff = window[f * dims + d] - mean[d];
      std[d] += diff * diff;
    }
  }
  for (let d = 0; d < dims; d++) std[d] = Math.sqrt(std[d] / frames) + 1e-5;

  const out = new Float32Array(frames * dims);
  const excludeVisibility = dims === FEATURE_DIM;
  for (let f = 0; f < frames; f++) {
    for (let d = 0; d < dims; d++) {
      const raw = window[f * dims + d];
      if (excludeVisibility && POSE_VIS_SET.has(d)) {
        out[f * dims + d] = Math.min(1, Math.max(0, raw));
      } else {
        out[f * dims + d] = (raw - mean[d]) / std[d];
      }
    }
  }
  return out;
}
