/**
 * Turns generated Markdown notes into downloadable files -- Markdown, a
 * styled plain-text version, and PDF -- entirely client-side. No backend
 * round-trip: by the time notes are on screen the full text already lives
 * in the browser, so there's nothing to fetch.
 *
 * The plain-text/PDF layout mirrors the "Suggested generated document"
 * format from the workplan (SIGN2NOTES header, date/duration, uppercase
 * section headers, bullet points, footer disclaimer).
 */

export interface ExportMeta {
  /** Lecture / session title, e.g. "DBMS Lecture 04". Defaults to "Lecture Notes". */
  title?: string;
  date?: Date;
  durationSeconds?: number;
}

function formatDuration(seconds?: number): string | null {
  if (seconds === undefined || seconds === null || !Number.isFinite(seconds)) return null;
  const total = Math.max(0, Math.round(seconds));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}

function formatDate(date?: Date): string {
  return (date ?? new Date()).toLocaleDateString(undefined, {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

/** One structured line of the notes, used by both the plain-text formatter
 * and the PDF renderer so the two stay visually consistent. */
type NoteLine =
  | { kind: "heading"; text: string }
  | { kind: "bullet"; text: string }
  | { kind: "para"; text: string }
  | { kind: "blank" };

function parseNoteLines(markdown: string): NoteLine[] {
  const lines: NoteLine[] = [];
  for (const raw of markdown.split("\n")) {
    const line = raw.trimEnd();
    const stripBold = (s: string) => s.replace(/\*\*(.+?)\*\*/g, "$1").replace(/\*(.+?)\*/g, "$1");

    if (/^#{1,3}\s+/.test(line)) {
      lines.push({ kind: "heading", text: stripBold(line.replace(/^#{1,3}\s+/, "")) });
    } else if (/^[-*]\s+/.test(line)) {
      lines.push({ kind: "bullet", text: stripBold(line.replace(/^[-*]\s+/, "")) });
    } else if (line.trim().length === 0) {
      lines.push({ kind: "blank" });
    } else {
      lines.push({ kind: "para", text: stripBold(line.trim()) });
    }
  }
  return lines;
}

/** Renders the SIGN2NOTES-styled plain-text document (see workplan section 7). */
export function markdownToPlainText(markdown: string, meta: ExportMeta = {}): string {
  const divider = "\u2500".repeat(40);
  const duration = formatDuration(meta.durationSeconds);

  const out: string[] = [
    "SIGN2NOTES",
    meta.title || "Lecture Notes",
    divider,
    `Date: ${formatDate(meta.date)}`,
  ];
  if (duration) out.push(`Duration: ${duration}`);
  out.push("");

  for (const line of parseNoteLines(markdown)) {
    if (line.kind === "heading") out.push("", line.text.toUpperCase());
    else if (line.kind === "bullet") out.push(`\u2022 ${line.text}`);
    else if (line.kind === "blank") out.push("");
    else out.push(line.text);
  }

  out.push("", divider, "Generated by Sign2Notes", "Prototype \u2014 limited vocabulary");
  return out.join("\n");
}

export function downloadTextFile(filename: string, content: string, mimeType = "text/plain") {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(filename: string, markdown: string) {
  downloadTextFile(filename, markdown, "text/markdown");
}

export function downloadPlainText(filename: string, markdown: string, meta: ExportMeta = {}) {
  downloadTextFile(filename, markdownToPlainText(markdown, meta), "text/plain");
}

/** Renders notes to a simple PDF via jsPDF, dynamically imported so the
 * library only loads for users who actually export to PDF. */
export async function downloadPdf(filename: string, markdown: string, meta: ExportMeta = {}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const marginX = 48;
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - marginX * 2;
  let y = 56;

  const ensureSpace = (need: number) => {
    if (y + need > pageHeight - 48) {
      doc.addPage();
      y = 56;
    }
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Sign2Notes", marginX, y);
  y += 26;

  doc.setFontSize(14);
  doc.text(meta.title || "Lecture Notes", marginX, y);
  y += 20;

  const duration = formatDuration(meta.durationSeconds);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110);
  doc.text(`Date: ${formatDate(meta.date)}${duration ? `    Duration: ${duration}` : ""}`, marginX, y);
  doc.setTextColor(20);
  y += 20;
  doc.setDrawColor(210);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 18;

  for (const line of parseNoteLines(markdown)) {
    if (line.kind === "blank") {
      y += 8;
      continue;
    }
    if (line.kind === "heading") {
      ensureSpace(24);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12.5);
      y += 8;
      doc.text(line.text.toUpperCase(), marginX, y);
      y += 16;
      continue;
    }
    const isBullet = line.kind === "bullet";
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    const prefix = isBullet ? "\u2022  " : "";
    const indent = isBullet ? 12 : 0;
    const wrapped = doc.splitTextToSize(prefix + line.text, maxWidth - indent);
    for (const w of wrapped) {
      ensureSpace(14);
      doc.text(w, marginX + indent, y);
      y += 14;
    }
  }

  ensureSpace(30);
  y += 10;
  doc.setDrawColor(210);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 16;
  doc.setFontSize(8.5);
  doc.setTextColor(140);
  doc.text("Generated by Sign2Notes \u2014 Prototype, limited vocabulary", marginX, y);

  doc.save(filename);
}

/** Slugifies a title into a safe filename stem, e.g. "DBMS Lecture 04" -> "dbms-lecture-04". */
export function slugify(title: string, fallback = "sign2notes"): string {
  const slug = title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  return slug || fallback;
}
